### ISSUE TITLE
关于AttributeError: 'SFFBlock' object has no attribute 'sf'问题无法解决

### ISSUE THREAD

**Issue by xiaobeial** [Zeyu-Zhu/TFDSUNet#2]
您好，作者，在复现你代码时候遇到AttributeError: 'SFFBlock' object has no attribute 'sf'这个问题一直无法解决，我检查代码并没有发现任何问题，如果您有解决方法，可以联系我的邮箱202270294116@hunnu.edu.cn，感谢！

**Comment by Zeyu-Zhu** [comment]
Could you inform me which code that you ran faced this problem?

**Comment by xiaobeial** [comment]
您好，这个问题我已经解决了，您在GitHub上的数据预处理部分代码是处理LG数据集的，请问可以给我发一份论文中的CALCE数据集的数据预处理文件吗？就是build_dataloader.py部分，感谢您！
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Oct 18, 2023 09:19 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [Zeyu-Zhu/TFDSUNet] 关于AttributeError: 'SFFBlock' object has no attribute 'sf'问题无法解决 (Issue #2)

&nbsp;



 
Could you inform me which code that you ran faced this problem?

**Comment by Zeyu-Zhu** [comment]
The normalization method we used for CALCE datasets is the same with LG, which you can easily apply the code we released for CALCE. Sorry that it's not convenient for us to give you the code you want.

**Comment by xryba7** [comment]
> 您好，作者，在复现你代码时候遇到AttributeError: 'SFFBlock' object has no attribute 'sf'这个问题一直无法解决，我检查代码并没有发现任何问题，如果您有解决方法，可以联系我的邮箱[202270294116@hunnu.edu.cn](mailto:202270294116@hunnu.edu.cn)，感谢！

您好，我也遇到了和你一样的问题，请问您是如何解决的呢？谢谢！
